permute([X,Y,Z,W],[X,Y,Z,W]).
permute([X,Y,Z,W],[X,Y,W,Z]).
permute([X,Y,Z,W],[X,W,Y,Z]).
permute([X,Y,Z,W],[X,W,Z,Y]).
permute([X,Y,Z,W],[X,Z,Y,W]).
permute([X,Y,Z,W],[X,Z,W,Y]).
permute([X,Y,Z,W],[Y,W,X,Z]).
permute([X,Y,Z,W],[Y,W,Z,X]).
permute([X,Y,Z,W],[Y,Z,X,W]).
permute([X,Y,Z,W],[Y,Z,W,X]).
permute([X,Y,Z,W],[Y,X,Z,W]).
permute([X,Y,Z,W],[Y,X,W,Z]).
permute([X,Y,Z,W],[Z,Y,X,W]).
permute([X,Y,Z,W],[Z,Y,W,X]).
permute([X,Y,Z,W],[Z,W,X,Y]).
permute([X,Y,Z,W],[Z,W,Y,X]).
permute([X,Y,Z,W],[Z,X,Y,W]).
permute([X,Y,Z,W],[Z,X,W,Y]).
permute([X,Y,Z,W],[W,Z,X,Y]).
permute([X,Y,Z,W],[W,Z,Y,X]).
permute([X,Y,Z,W],[W,Y,X,Z]).
permute([X,Y,Z,W],[W,Y,Z,X]).
permute([X,Y,Z,W],[W,X,Y,Z]).
permute([X,Y,Z,W],[W,X,Z,Y]).
permute([X,Y,Z],[X,Y,Z]).
permute([X,Y,Z],[X,Z,Y]).
permute([X,Y,Z],[Z,Y,X]).
permute([X,Y,Z],[Z,X,Y]).
permute([X,Y,Z],[Y,Z,X]).
permute([X,Y,Z],[Y,X,Z]).
permute([X,Y],[Y,X]).
permute([X,Y],[X,Y]).